server:
  port: 9000
spring:
  data:
    mongodb:
      uri: "mongodb://localhost:27017/fitnessactivity"
      database: "fitnessactivity"
  cloud:
    function:
      definition: fitnessDetails
    stream:
      bindings:
        fitnessDetails-in-0:
          destination: send-fitness-details
          group: ${spring.application.name}

eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: "http://localhost:8070/eureka"

logging:
  level:
    com:
      AyushToCode:
        AIService: DEBUG

