services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: fitnessactivity
    extends:
      file: common-config.yml
      service: network-deploy-service

  keycloak:
    image: quay.io/keycloak/keycloak:26.2.1
    container_name: keycloak
    ports:
      - "7080:8080"
    environment:
      KEYCLOAK_ADMIN: "admin"
      KEYCLOAK_ADMIN_PASSWORD: "admin"
    command: "start-dev"
    extends:
      file: common-config.yml
      service: network-deploy-service

  fitness_user_db:
    image: mysql
    container_name: fitness_user_db
    ports:
      - 3307:3306
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 10s
      retries: 10
      interval: 10s
      start_period: 10s
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: fitness_user_db
    extends:
      file: common-config.yml
      service: microservice-base-config

  rabbit:
    image: rabbitmq:4.0-management
    hostname: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 5s
    extends:
      file: common-config.yml
      service: network-deploy-service

  configserver:
    image: "imak070504/configserver:s1"
    container_name: configserver-ms
    ports:
      - "8071:8071"
    healthcheck:
      test: "curl --fail --silent localhost:8071/actuator/health/readiness | grep UP || exit 1"
      interval: 20s
      timeout: 5s
      retries: 20
      start_period: 10s
    extends:
      file: common-config.yml
      service: microservice-base-config

  eurekaserver:
    image: "imak070504/eurekaserver:s1"
    container_name: eurekaserver-ms
    ports:
      - "8070:8070"
    depends_on:
      configserver:
        condition: service_healthy
    healthcheck:
      test: "curl --fail --silent localhost:8070/actuator/health/readiness | grep UP || exit 1"
      interval: 20s
      timeout: 5s
      retries: 20
      start_period: 10s
    extends:
      file: common-config.yml
      service: microservice-configserver-config
    environment:
      SPRING_APPLICATION_NAME: "eurekaserver"

  aiservice:
    image: "imak070504/aiservice:s1"
    container_name: aiservice-ms
    depends_on:
      eurekaserver:
        condition: service_healthy
      rabbit:
        condition: service_healthy
    healthcheck:
      test: "curl --fail --silent localhost:9000/actuator/health/readiness | grep UP || exit 1"
      interval: 20s
      timeout: 5s
      retries: 20
      start_period: 10s
    environment:
      SPRING_APPLICATION_NAME: "AIService"
      SPRING_RABBITMQ_HOST: "rabbit"
      SPRING_DATA_MONGODB_URI: "mongodb://mongodb:27017/fitnessactivity"
    extends:
      file: common-config.yml
      service: microservice-eureka-config

  activityservice:
    image: "imak070504/activityservice:s1"
    container_name: activityservice-ms
    depends_on:
      eurekaserver:
        condition: service_healthy
    healthcheck:
      test: "curl --fail --silent localhost:8090/actuator/health/readiness | grep UP || exit 1"
      interval: 20s
      timeout: 5s
      retries: 20
      start_period: 10s
    environment:
      SPRING_APPLICATION_NAME: "ActivityService"
      SPRING_RABBITMQ_HOST: "rabbit"
      SPRING_DATA_MONGODB_URI: "mongodb://mongodb:27017/fitnessactivity"
    extends:
      file: common-config.yml
      service: microservice-eureka-config

  userservice:
    image: "imak070504/userservice:s1"
    container_name: userservice-ms
    depends_on:
      eurekaserver:
        condition: service_healthy
      fitness_user_db:
        condition: service_healthy
    healthcheck:
      test: "curl --fail --silent localhost:8080/actuator/health/readiness | grep UP || exit 1"
      interval: 20s
      timeout: 5s
      retries: 20
      start_period: 10s
    environment:
      SPRING_APPLICATION_NAME: "UserService"
      SPRING_DATASOURCE_URL: "jdbc:mysql://fitness_user_db:3306/fitness_user_db"
    extends:
      file: common-config.yml
      service: microservice-eureka-config

  gatewayserver:
    image: "imak070504/gatewayserver:s1"
    container_name: gatewayserver-ms
    ports:
      - "8072:8072"
    depends_on:
      userservice:
        condition: service_healthy
      activityservice:
        condition: service_healthy
      aiservice:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: "gatewayserver"
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK-SET-URI: "http://keycloak:8080/realms/FitnessApp/protocol/openid-connect/certs"
    extends:
      file: common-config.yml
      service: microservice-eureka-config


networks:
  fitness:
    driver: "bridge"